Add Missing Type Annotations
adafruit/Adafruit_CircuitPython_Trellis pull request #20
Opened 2022-09-07 15:36 UTC by tcfranks

resolves #18 
submitted for review / comment

2022-09-07 21:04 UTC, tekktrik requested changes
Great work!  Feedback below:

2022-09-07 21:04 UTC, tekktrik commented on adafruit_trellis.py
> +    def blink_rate(self) -> int:
This should match the setter, I think `Literal` is the way to go.

2022-09-07 21:04 UTC, tekktrik commented on adafruit_trellis.py
> +    def brightness(
That's a pretty big `Literal`, for the sake of readability let's just use `int`.  The real answer would be to use `Enum` but that's not currently supported by CircuitPython.

2022-09-07 21:04 UTC, tekktrik commented on adafruit_trellis.py
> +    def __init__(self, i2c: I2C, addresses: Optional[int] = None) -> None:
Looks like `addresses` should be `Optional[List[int]]`

2022-09-08 02:55 UTC, tcfranks commented on adafruit_trellis.py
> +    def __getitem__(self, x: int) -> None:
oops, I see that now

2022-09-08 03:03 UTC, tcfranks commented
resubmitted with changes

2022-09-08 03:20 UTC, tekktrik approved these changes
Looks good, thanks!

2022-09-08 03:20 UTC, merged